### ISSUE TITLE
[Bug]: Crash on startup.

### ISSUE THREAD

**Issue by Ensou1** [bonsaistudi0s/EndermanOverhaul#37]
### Bug Description

attempted with all forge 1.19.2 versions. Tried with and without other mods installed. 

### How to Reproduce?

.

### Expected Behavior

.

### Version

1.0.0

### Mod Loader Version

1.19.2-43.2.21

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
You are not providing any info; I need a crash report. And 1.0.0 is for 1.20.1
