### ISSUE TITLE
Ignore this

### ISSUE THREAD

**Issue by HariboTer** [bonsaistudi0s/EndermanOverhaul#39]
### Bug Description

Using the following versions:
Minecraft 1.19.2
Forge 43.3.0
geckolib-forge 3.1.40
resourcefulconfig-forge 1.0.20
endermanoverhaul-forge 0.0.1

and no other mods, it will still crash on startup every time.

The logs hint towards the mod looking for some classes from resourceful lib, which of course don't exist because that library is not available for 1.19.2. I tried to get it working with its 1.20.1 version (2.1.21) but that did unfortunately not work either.

### How to Reproduce?

Try to launch the mod configuration mentioned above, the minimal expected setup that should get this mod to work. Instead of launching, the game crashes with a rather unspecified error before getting to the loading bar.

### Expected Behavior

The mod should be loaded successfully.

### Version

0.0.1

### Mod Loader Version

1.19.2 - 43.3.0

### Mod Loader

Forge

### Logs or additional context

[pool-3-thread-1/WARN] [mixin/]: Error loading class: com/teamresourceful/resourcefullib/common/registry/RegistryEntry (java.lang.ClassNotFoundException: com.teamresourceful.resourcefullib.common.registry.RegistryEntry)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [ ] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
you’re missing resourceful lib

**Comment by HariboTer** [comment]
Edit: Please forget this, I stayed up too long and for some reason got convinced that Resourceful Lib was only available for Minecraft 1.20 upwards.

**Comment by AlexNijjar** [comment]
I'm so confused. Enderman Overhaul has 3 dependencies and you are missing one of them: `Resourceful Lib`. Install it and it'll work fine https://legacy.curseforge.com/minecraft/mc-mods/resourceful-lib
<img width="891" alt="Screenshot 2024-01-31 at 4 14 37 PM" src="https://github.com/bonsaistudi0s/Enderman-Overhaul/assets/61668546/a0767ac3-279e-4040-8bfb-76900d6d11ec">

**Comment by HariboTer** [comment]
My apologies. Somehow it got etched into my memory that there was no version of Resourceful Lib for 1.19.2 so my surprise was rather palpable when I just double-checked to discover 1.19.2 being available for selection >.<

Again, please excuse my error, it's all running well and proper now!
