### ISSUE TITLE
[Bug]: None of the new enderman are spawning

### ISSUE THREAD

**Issue by CyrusGB** [bonsaistudi0s/EndermanOverhaul#42]
### Bug Description

I am playing on forge 1.20.1 with Enderman overhaul and Creeper overhaul but none of the new entities seem to be spawning. I have been flying around in spectator for hours looking for any of them using "/effect give @e[type=endermanoverhaul:cave_enderman] minecraft:glowing infinite" to try to make it easier. 

Maybe I'm missing something because I cant find any other info on my issue.

### How to Reproduce?

1. Create new world
2. Find no new enderman or creepers

### Version

1.0.4

### Mod Loader Version

1.20.1 - 47.2.17

### Logs or additional context

Log of session vvv
https://mclo.gs/dn2jNWp

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Lucas-Carrarini** [comment]
Same here, only found in The End one variation, and that's all
Should be an option to increase each variation or endermans in general, but endermans still spawning frequently, maybe consider replace the normal enderman spawn to the modded ones for the respective biome
Same on Creeper Overhaul

**Comment by MrUnicycle** [comment]
Has anybody found a solution to this issue? Straight up not getting any spawns from this mod _ever_
