### ISSUE TITLE
[Bug]: "Shift-right click to bind an entity" should be renamed to "Crouch + Right-Click to bind an entity"

### ISSUE THREAD

**Issue by nco2k** [bonsaistudi0s/EndermanOverhaul#48]
### Bug Description

see title. :)

### Version

1.1.8

### Mod Loader Version

1.20.4 - 0.15.9

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Why?

**Comment by nco2k** [comment]
because its crouch + right click, and not shift + right click. if you rebind crouch to ctrl, then you will have to press ctrl + right click in order for it to work. but the message will still wrongfully tell you to press shift + right click.

**Comment by AlexNijjar** [comment]
With that logic, right-click would need to be renamed as well since the interaction keybind can be remapped. But for now, sure, I'll rename it
