### ISSUE TITLE
[Feature Request]: Vanilla Enderman Override Config Option (1.19.2)

### ISSUE THREAD

**Issue by ScoutTheSaneless** [bonsaistudi0s/EndermanOverhaul#53]
### Is your feature request related to a problem?

I would like a config option to have the mod disallow the overriding of the vanilla enderman model, much like the Creeper Overhaul mod

### Solution(s)

What's said on the tin

### Mod Version

0.0.1

### Mod Loader Version

1.19.2-43.3.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
Please use this jar. https://github.com/bonsaistudi0s/Enderman-Overhaul/issues/12#issuecomment-1763211366

**Comment by ScoutTheSaneless** [comment]
im in need of a version i can safely post in a modpack, may i use that one if i post to CF?

**Comment by AlexNijjar** [comment]
you may not repost the mod. I’ll update it

**Comment by ScoutTheSaneless** [comment]
thank you for the response back!

**Comment by AlexNijjar** [comment]
uploaded
