### ISSUE TITLE
[Bug]: default enderman texture

### ISSUE THREAD

**Issue by Yolkest** [bonsaistudi0s/EndermanOverhaul#58]
### Bug Description

![2024-06-24_02 10 46](https://github.com/bonsaistudi0s/Enderman-Overhaul/assets/173133270/7b3279c8-b876-4fc8-ab79-689766da2838)

I saw an enderman (with the enderman overhaul mod installed) in my house and took a look at it and noticed the underside of its head was transparent (mainly the jaw) and because I don't have any mods that alter the model of the enderman, it has to be a texture bug.

P.S. I love both creeper and enderman overhauls and especially like the cave enderman, scared the crap out of me the first time. keep up the awesome work :D

### Version

0.0.0

### Mod Loader Version

1.19.2 - 0.15.7

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Seems to be a 1.19.2-specific issue as the texture is fine in newer versions. This likely won't be fixed as 1.19.2 is no longer supported. Thanks for the kind words!
<img width="1512" alt="Screenshot 2024-07-06 at 12 19 31 AM" src="https://github.com/bonsaistudi0s/Enderman-Overhaul/assets/61668546/dee3c67a-07ee-4759-94de-f238c0e6e5a7">
