### ISSUE TITLE
Enderman sounds have no distance falloff and mushroom fields endermen lack animations [QUILT]

### ISSUE THREAD

**Issue by crowsWithHats** [bonsaistudi0s/EndermanOverhaul#6]
I'm on quilt using the mod and the new enderman noises have no distance falloff (it can be underground 20 blocks below you and it sounds like it's right next to you) as well as the Mushroom Fields endermen lacking a walking animation.

**Comment by AlexNijjar** [comment]
Fixed in b37e220
