### ISSUE TITLE
1.21 for fabric?

### ISSUE THREAD

**Issue by Hugs288** [bonsaistudi0s/EndermanOverhaul#65]
### Is your feature request related to a problem?

-

### Solution(s)

-

### Describe alternatives you've considered

-

### Mod Version

-

### Mod Loader Version

-

**Comment by AlexNijjar** [comment]
fabric is no longer supported in 1.21.

**Comment by Panzimy** [comment]
Hello I have a question I see that you are not planning a minecraft 1.21 fabric version but why?
