### ISSUE TITLE
[Bug]: 1.21.1 Cannot craft Corrupted item

### ISSUE THREAD

**Issue by SkyRunner55** [bonsaistudi0s/EndermanOverhaul#76]
### Bug Description

You cannot craft Corrupted Blade & Shield

### How to Reproduce?

Just play the game and notice you can't craft it

### Expected Behavior

you can craft both

### Version

1.21-2.0.0

### Mod Loader Version

21.1.80

### Mod Loader

NeoForge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
fixed a93f02e6de44d444e192aef6313858659d3e7e25
