### ISSUE TITLE
Crash when enabling shaders

### ISSUE THREAD

**Issue by YassaaaTU** [bonsaistudi0s/EndermanOverhaul#8]
When I enabled shaders the game just froze then crashed.
Check the crash report: https://mclo.gs/a7OwjcR

Minecraft version: 1.20.1
Modpack: ATM9 - BUT HEAVILY MODIFIED by me
Mod Version: 1.0.0
Gecko Lib: 4.2.1

Shaders used: Complementary Shaders - Unbound 5.0.1

**Comment by AlexNijjar** [comment]
<img width="1156" alt="Screenshot 2023-10-14 at 12 07 14 PM" src="https://github.com/bonsaistudi0s/EndermanOverhaul/assets/61668546/5314e968-735e-4dd8-bc3f-7e6c03e893c2">
you have an outdated version of geckolib
