### ISSUE TITLE
[Bug]: Resourceful Config Dependency Error

### ISSUE THREAD

**Issue by jaeggr** [bonsaistudi0s/EndermanOverhaul#80]
### Bug Description

Version 1.21.1-2.0.2 seems to require Resourceful Config version 3.0.7 or above, even though the latest version available to MC 1.21.1 is 3.0.4 (3.4.1 is the latest Resourceful Config NeoForge version for MC 1.21.4). Versions later than 3.0.4 won't work.

```
-- Mod loading issue for: endermanoverhaul --
Details:
	Mod file: /D:/CurseForge/Instances/NoO1/mods/endermanoverhaul-neoforge-1.21.1-2.0.2.jar
	Failure message: Mod endermanoverhaul requires resourcefulconfig 3.0.7 or above
		Currently, resourcefulconfig is 3.0.4
		
	Mod version: 2.0.2
	Mod issues URL: https://github.com/bonsaistudi0s/endermanoverhaul/issues
	Exception message: <No associated exception found>
```

### How to Reproduce?

Load latest 2.0.2 with latest Resourceful Config for MC 1.21.1 (3.0.4)

### Version

2.0.2

### Mod Loader Version

21.1.84

### Mod Loader

NeoForge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
the latest version for 1.21.1 is 3.0.8

https://www.curseforge.com/minecraft/mc-mods/resourceful-config/files/5808466
https://modrinth.com/mod/resourceful-config/version/3.0.8
