### ISSUE TITLE
Endermen overhaul no sound fall-off

### ISSUE THREAD

**Issue by CodySpirits1** [bonsaistudi0s/EndermanOverhaul#9]
Hey, I'm using the 1.0.0 Forge version, and it appears every enderman variants that use new/original sounds have no sound fall-off over distance for any of the sounds they make, some of which are quite loud.
Other than that, very solid mod!

**Comment by AlexNijjar** [comment]
duplicate of #6 and fixed in 1.0.1.

**Comment by AlexNijjar** [comment]
(1.0.1 is currently being uploaded)
